// src/pages/404.tsx
import MaxWidthWrapper from "~/components/MaxWidthWrapper";
import DefaultLayout from "~/layouts/Default";
export default function Custom404() {
  return (
    <DefaultLayout>
      <MaxWidthWrapper>
        <h1>Whoops! Page can't be found.</h1>
        <p>
          It looks like you're trying to access a page that can't be found. This
          could be because the URL used to get here is incorrect.
        </p>
        <p>
          Let me know you stumbled onto a broken link on{" "}
          <a href="https://twitter.com/chaseadamsio">Twitter</a>!
        </p>
      </MaxWidthWrapper>
    </DefaultLayout>
  );
}

// src/pages/404.vue
<template>
  <Layout>
    <PrimaryHeader title="Whoops! Page can't be found." />
    <div class="text-center">
      <p>
        It looks like you're trying to access a page that can't be found. <br />
        This could be because the URL used to get here is incorrect.
      </p>
      <p>
        <TwitterNotifyLink />
      </p>
    </div>
  </Layout>
</template>

<script>
import PrimaryHeader from "../components/PrimaryHeader";
import TwitterNotifyLink from "../components/TwitterNotifyLink";

export default {
  components: {
    PrimaryHeader,
    TwitterNotifyLink,
  },
  metaInfo: {
    title: "Whoops! Page can't be found",
  },
};
</script>
