// src/pages/About.vue
<template>
  <Layout>
    <PrimaryHeader title="About Me" />
    <div class="post-content">
      <div>
        <h2>In 30 Seconds</h2>
        <h3>I enjoy...</h3>
        <ul>
          <li>
            🧰building software that lowers friction so that makers can turn
            their ideas into reality.
          </li>
          <li>👨‍🔬learning new concepts and ideas.</li>
          <li>🚀teaching others.</li>
          <li>🧠exploring ideas on consciousness.</li>
        </ul>

        <h3>Now...</h3>

        <ul>
          <li>🦄 I build software at [Webflow](http://webflow.com/).</li>
          <li>
            🧪 I experiment with various tools, systems & processes to learn to
            live more effectively.
          </li>
          <li>↗️ My favorite shape is an arrow.</li>
          <li>🏜 I live in Las Vegas, Nevada, USA.</li>
          <li>
            📚 Currently Reading...
            <ul>
              <li>**Essentialism** by Gregory McKeown</li>
              <li>**Finite &amp; Infinite Games** by James Carse</li>
            </ul>
          </li>
        </ul>
      </div>
      <div>
        <h2>At Work, I'm...</h2>
        <ul>
          <li>Improving the development toolchain for developer happiness.</li>
          <li>Helping others learn &amp; use systems thinking.</li>
          <li>
            Building better continuous integration &amp; delivery pipelines for
            Webflow's software to be deployed often, quickly &amp; safely.
          </li>
          <li>
            Mentoring other individual contributors in building better software
            &amp; personal development.
          </li>
        </ul>
      </div>
      <div>
        <h2>At Home, I'm...</h2>
        <ul>
          <li>Hiking &amp; birding with my wife &amp; daughter.</li>
          <li>Hanging out with my awesome family.</li>
          <li>Walking my dogs.</li>
          <li>Building train tracks with my daughter.</li>
          <li>Making cold brew coffees &amp; Americanos.</li>
        </ul>
      </div>
      <div>
        <h2>My Interests Include...</h2>
        <ul>
          <li>Experimenting with productivity systems &amp; processes.</li>
          <li>Making things with my 3D printer.</li>
          <li>Hacking on software ideas.</li>
          <li>Writing about the process of building software.</li>
          <li>Reading and reviewing books.</li>
          <li>Teaching others about technology &amp; productivity.</li>
        </ul>
      </div>
    </div>
  </Layout>
</template>

<script>
import PrimaryHeader from "../components/PrimaryHeader";
export default {
  components: {
    PrimaryHeader,
  },
  metaInfo: {
    title: "About Chase",
    description: "Learn about Chase Adams: Engineering and Experimentation",
  },
};
</script>

// src/views/About/index.tsx
import Head from "next/head";

import { Container } from "~/components/shared/Container";
import { PageContainer } from "~/components/shared/PageContainer";
import ViewH1 from "~/components/shared/PageTitle";
import { SiteFooter } from "~/components/SiteFooter";
import { SiteHeader } from "~/components/SiteHeader";

export const AboutView = () => {
  return (
    <>
      <Head>
        <title>About Me - Chase Adams</title>
      </Head>
      <PageContainer>
        <SiteHeader />
        <Container>
          <ViewH1>About Me</ViewH1>
          <h2>In 30 Seconds</h2>
          <h3>I enjoy...</h3>
          <ul className="list-disc pl-4 py-4">
            <li className="ml-8 py-1">
              🧰 building software that lowers friction so that makers can turn
              their ideas into reality.
            </li>
            <li className="ml-8 py-1">👨‍🔬 learning new concepts and ideas.</li>
            <li className="ml-8 py-1">🚀 teaching others.</li>
            <li className="ml-8 py-1">🧠 exploring ideas on consciousness.</li>
          </ul>
          <h2>Now...</h2>
          <ul className="list-disc pl-4 py-4">
            <li className="ml-8 py-1">
              🦄 I build software at <a href="https://murmur.com">Murmur</a>.
            </li>
            <li className="ml-8 py-1">
              🧪 I experiment with various tools, systems & processes to learn
              to live more effectively.
            </li>
            <li className="ml-8 py-1">↗️ My favorite shape is an arrow.</li>
            <li className="ml-8 py-1">🏜 I live in Las Vegas, Nevada, USA.</li>
          </ul>
          <h3>At Home, I'm...</h3>
          <ul className="list-disc pl-4 py-4">
            <li className="ml-8 py-1">
              Hiking & birding with my wife & daughter.
            </li>
            <li className="ml-8 py-1">Hanging out with my awesome family.</li>
            <li className="ml-8 py-1">Walking my dogs.</li>
            <li className="ml-8 py-1">
              Building train tracks with my daughter.
            </li>
            <li className="ml-8 py-1">
              Making cold brew coffees & Americanos.
            </li>
          </ul>
          <h3>My Interests Include...</h3>
          <ul className="list-disc pl-4 py-4">
            <li className="ml-8 py-1">
              Experimenting with productivity systems & processes.
            </li>
            <li className="ml-8 py-1">Making things with my 3D printer.</li>
            <li className="ml-8 py-1">Hacking on software ideas.</li>
            <li className="ml-8 py-1">
              Writing about the process of building software.
            </li>
            <li className="ml-8 py-1">Reading and reviewing books.</li>
            <li className="ml-8 py-1">
              Teaching others about technology & productivity.
            </li>
          </ul>
        </Container>

        <SiteFooter />
      </PageContainer>
    </>
  );
};
